export const TAROT_CARDS = [
  // Major Arcana
  { id: 'fool', name: 'The Fool', suit: 'major' },
  { id: 'magician', name: 'The Magician', suit: 'major' },
  { id: 'high_priestess', name: 'The High Priestess', suit: 'major' },
  { id: 'empress', name: 'The Empress', suit: 'major' },
  { id: 'emperor', name: 'The Emperor', suit: 'major' },
  { id: 'hierophant', name: 'The Hierophant', suit: 'major' },
  { id: 'lovers', name: 'The Lovers', suit: 'major' },
  { id: 'chariot', name: 'The Chariot', suit: 'major' },
  { id: 'strength', name: 'Strength', suit: 'major' },
  { id: 'hermit', name: 'The Hermit', suit: 'major' },
  { id: 'wheel', name: 'Wheel of Fortune', suit: 'major' },
  { id: 'justice', name: 'Justice', suit: 'major' },
  { id: 'hanged', name: 'The Hanged Man', suit: 'major' },
  { id: 'death', name: 'Death', suit: 'major' },
  { id: 'temperance', name: 'Temperance', suit: 'major' },
  { id: 'devil', name: 'The Devil', suit: 'major' },
  { id: 'tower', name: 'The Tower', suit: 'major' },
  { id: 'star', name: 'The Star', suit: 'major' },
  { id: 'moon', name: 'The Moon', suit: 'major' },
  { id: 'sun', name: 'The Sun', suit: 'major' },
  { id: 'judgement', name: 'Judgement', suit: 'major' },
  { id: 'world', name: 'The World', suit: 'major' },
  
  // Wands
  { id: 'ace_wands', name: 'Ace of Wands', suit: 'wands' },
  { id: 'two_wands', name: 'Two of Wands', suit: 'wands' },
  { id: 'three_wands', name: 'Three of Wands', suit: 'wands' },
  { id: 'four_wands', name: 'Four of Wands', suit: 'wands' },
  { id: 'five_wands', name: 'Five of Wands', suit: 'wands' },
  { id: 'six_wands', name: 'Six of Wands', suit: 'wands' },
  { id: 'seven_wands', name: 'Seven of Wands', suit: 'wands' },
  { id: 'eight_wands', name: 'Eight of Wands', suit: 'wands' },
  { id: 'nine_wands', name: 'Nine of Wands', suit: 'wands' },
  { id: 'ten_wands', name: 'Ten of Wands', suit: 'wands' },
  { id: 'page_wands', name: 'Page of Wands', suit: 'wands' },
  { id: 'knight_wands', name: 'Knight of Wands', suit: 'wands' },
  { id: 'queen_wands', name: 'Queen of Wands', suit: 'wands' },
  { id: 'king_wands', name: 'King of Wands', suit: 'wands' },
  
  // Cups
  { id: 'ace_cups', name: 'Ace of Cups', suit: 'cups' },
  { id: 'two_cups', name: 'Two of Cups', suit: 'cups' },
  { id: 'three_cups', name: 'Three of Cups', suit: 'cups' },
  { id: 'four_cups', name: 'Four of Cups', suit: 'cups' },
  { id: 'five_cups', name: 'Five of Cups', suit: 'cups' },
  { id: 'six_cups', name: 'Six of Cups', suit: 'cups' },
  { id: 'seven_cups', name: 'Seven of Cups', suit: 'cups' },
  { id: 'eight_cups', name: 'Eight of Cups', suit: 'cups' },
  { id: 'nine_cups', name: 'Nine of Cups', suit: 'cups' },
  { id: 'ten_cups', name: 'Ten of Cups', suit: 'cups' },
  { id: 'page_cups', name: 'Page of Cups', suit: 'cups' },
  { id: 'knight_cups', name: 'Knight of Cups', suit: 'cups' },
  { id: 'queen_cups', name: 'Queen of Cups', suit: 'cups' },
  { id: 'king_cups', name: 'King of Cups', suit: 'cups' },
  
  // Swords
  { id: 'ace_swords', name: 'Ace of Swords', suit: 'swords' },
  { id: 'two_swords', name: 'Two of Swords', suit: 'swords' },
  { id: 'three_swords', name: 'Three of Swords', suit: 'swords' },
  { id: 'four_swords', name: 'Four of Swords', suit: 'swords' },
  { id: 'five_swords', name: 'Five of Swords', suit: 'swords' },
  { id: 'six_swords', name: 'Six of Swords', suit: 'swords' },
  { id: 'seven_swords', name: 'Seven of Swords', suit: 'swords' },
  { id: 'eight_swords', name: 'Eight of Swords', suit: 'swords' },
  { id: 'nine_swords', name: 'Nine of Swords', suit: 'swords' },
  { id: 'ten_swords', name: 'Ten of Swords', suit: 'swords' },
  { id: 'page_swords', name: 'Page of Swords', suit: 'swords' },
  { id: 'knight_swords', name: 'Knight of Swords', suit: 'swords' },
  { id: 'queen_swords', name: 'Queen of Swords', suit: 'swords' },
  { id: 'king_swords', name: 'King of Swords', suit: 'swords' },
  
  // Coins
  { id: 'ace_coins', name: 'Ace of Coins', suit: 'coins' },
  { id: 'two_coins', name: 'Two of Coins', suit: 'coins' },
  { id: 'three_coins', name: 'Three of Coins', suit: 'coins' },
  { id: 'four_coins', name: 'Four of Coins', suit: 'coins' },
  { id: 'five_coins', name: 'Five of Coins', suit: 'coins' },
  { id: 'six_coins', name: 'Six of Coins', suit: 'coins' },
  { id: 'seven_coins', name: 'Seven of Coins', suit: 'coins' },
  { id: 'eight_coins', name: 'Eight of Coins', suit: 'coins' },
  { id: 'nine_coins', name: 'Nine of Coins', suit: 'coins' },
  { id: 'ten_coins', name: 'Ten of Coins', suit: 'coins' },
  { id: 'page_coins', name: 'Page of Coins', suit: 'coins' },
  { id: 'knight_coins', name: 'Knight of Coins', suit: 'coins' },
  { id: 'queen_coins', name: 'Queen of Coins', suit: 'coins' },
  { id: 'king_coins', name: 'King of Coins', suit: 'coins' }
]

export const CARD_LOOKS = ['Look 1', 'Look 2', 'Look 3']
